---
title: "cv"
output: 
blogdown::html_page:
  toc:TRUE
---
# Experience and Skills 

### Data Analysis
  * Created training and test data sets and tested predictive performance of machine learning models to determine lactose amount from dietary recall data   
  *	Evaluated database matching methods to match foods between different food and nutrient databases   
  *	Experience with dietary intake data: determining association of lactase persistence genetics with dairy consumption from dietary data and other markers of health using a variety of statistical analyses  
  *	Assisted with quality control (QC) of dual-energy x-ray absorptiometry (DEXA) for a large, cross-sectional human nutrition study  
  *	QC’d short chain fatty acid (SCFA) data and evaluated the relationship with respect to stool pH, DEXA variables, and dietary fiber and calcium intake. The results contributed to the decision making for extraction and analysis of additional SCFA samples   
  *	Manipulation, analysis, integration and biological interpretation of “Big Data” (transcriptomic, proteomic, and metabolomic data) to track metabolism changes in diseased plants  
  * “Big Data” statistical analyses included: univariate and multivariate (both supervised, unsupervised) statistical methods, performed data pre-processing and transformation prior to analysis, and multidimensional data visualization   

### Computational
* Proficient in the statistical programming language R 
* Regularly uses Python and Jupyter Notebooks
* Use of shell scripting with a compute cluster (UC Davis FARM) and cloud computing servings (Amazon Web Services) for RNA-seq analysis 
* Experience implementing software on Unix and HPC using SLURM submission scheduling
* Documenting work and organizing scripts with Git/GitHub and R Markdown

### Communication
* Led and organized an “Intro to R” mini-workshop series for lab meetings. Workshop will be expanded to include all USDA Davis, CA area employees 
* Supervised undergraduate researchers conducting quality control of dietary data. Taught undergraduate students basic techniques for data management and writing reproducible code
* Experienced with scientific manuscript preparation for peer-reviewed journals
* Shared research findings to citrus growers, academic and government scientists, and industry members through oral and poster presentations at scientific meetings during Ph.D.
* Translated complex scientific ideas to citrus growing community by writing lay articles and designing accompanying graphics for the magazine Citrograph 
* Independently contracted by a USDA lab to design non-technical flyers to share the findings from a study that evaluated the nutritional quality and consumer acceptability of persimmons. Flyers were distributed to persimmon growers, producers, and consumers

### Laboratory     
* Planned and conducted experiments in small greenhouse and large field settings 
* Protocol development: non-hazardous, low waste polar metabolite extraction protocol; RNA extraction protocol from citrus leaves; rapid, automated assay for evaluation of antimicrobial efficacy 
* Operation of 600 MHz NMR and targeted and untargeted analysis of 1H NMR spectra
* Antioxidant evaluation of various food using HPLC, GC-MS, Oxygen Radical Absorbance Capacity (ORAC), and Trolox equivalent assay

# Research Positions

USDA | Davis, CA.............................................................................................2019 - Present  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Computational Biologist Research Associate | Laboratory of Danielle Lemay, Ph.D.  
 
UC Davis Genome Center | Davis, CA...................................................................2018 – 2019  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Postdoctoral Researcher | Laboratory of Danielle Lemay, Ph.D.   

UC Davis Food Science and Technology | Davis, CA    				        
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Postdoctoral Researcher | Laboratory of Carolyn Slupsky, Ph.D............................2017 – 2018  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Graduate Student Researcher | Laboratory of Carolyn Slupsky, Ph.D.....................2012 – 2017  

PepsiCo | Valhalla, NY.......................................................................................2011  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Research and Development Intern | Supervised by Richard Smith, Ph.D.

The Hershey Co. | Hershey, PA............................................................................2010  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Research and Development Intern | Supervised by Dan Sweigart, Ph.D.

Virginia Tech Food Science Department | Blacksburg, VA.........................................2008 - 2011  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Undergraduate Research Assistant | Laboratory by Sean O’Keefe, Ph.D.



# Education
Ph.D. in Food Science and Technology | University of California, Davis......................August 2017   
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Dissertation: *Changes in Citrus Metabolism During Candidatus Liberibacter asiaticus Infection*  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Advisor: Carolyn Slupsky, Ph.D.  

B.S. in Food Science and Technology & Biological Sciences | Virginia Tech................ 2008 – 2012  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Minor: Chemistry  

